spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: default
  config:
    import:
      - optional:classpath:migConf.yml

logging:
  level:
    com.wolfhouse: debug